spring.application.name=property-booking-website
spring.datasource.url=jdbc:mysql://localhost:3306/booking_user
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8081
jwt.secret=mySecretKeyForJWTGeneration23212321123113
jwt.expiration=8640000000
spring.mongodb.uri=mongodb://localhost:27017/booking_property
